#####测试环境
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #连接超时时间
    timeout: 50000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dch.entity.Test
